version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: car-repair-billing-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=car_repair_billing;Username=postgres;******
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
    ports:
      - '8080:8080'

  postgres:
    image: postgres:16-alpine
    container_name: car-repair-billing-postgres
    environment:
      POSTGRES_DB: car_repair_billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d car_repair_billing']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: car-repair-billing-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
