sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/bin/**,**/obj/**
sonar.coverage.exclusions=**/Migrations/**,**/*Program.cs
sonar.cs.opencover.reportsPaths=TestResults/**/coverage.opencover.xml
